/// Flutter icons Human
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Human
///      fonts:
///       - asset: fonts/Human.ttf
///
/// 
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
/// * MFG Labs, Copyright (C) 2012 by Daniel Bruce
///         Author:    MFG Labs
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.mfglabs.com/
///
import 'package:flutter/widgets.dart';

class Human {
  Human._();

  static const _kFontFam = 'Human';
  static const String? _kFontPkg = null;

  static const IconData goalalogo = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData adult = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData child = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData globe = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData globe_alt = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xf061, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
